# Generated by Django 3.2.7 on 2022-10-17 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_staff_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='managestaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='personimages')),
                ('description', ckeditor.fields.RichTextField()),
                ('linkedin_adress', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
