# Generated by Django 3.2.7 on 2022-10-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_managestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='managestaff',
            name='instagram_adress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='managestaff',
            name='mail',
            field=models.TextField(null=True),
        ),
    ]
