# Generated by Django 3.2.7 on 2022-10-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeintro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homeintimages')),
                ('header', models.CharField(max_length=50)),
                ('explanation', models.CharField(max_length=250)),
            ],
        ),
    ]
