# Generated by Django 3.2.7 on 2022-10-25 08:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_homeintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teamimages')),
                ('header', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='homeintro',
            name='explanation',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
