# Generated by Django 3.2.7 on 2022-10-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_auto_20221025_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='instagram_adress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='linkedin_adress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='mail',
            field=models.TextField(null=True),
        ),
    ]
